# Generated by Django 5.2.4 on 2025-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('footwear', 'Footwear'), ('books', 'Books'), ('home', 'Home & Garden'), ('sports', 'Sports')], default='electronics', max_length=20),
        ),
    ]
